version: 2
updates:
  # Maintain dependencies for Python/pip
  - package-ecosystem: "pip"
    directory: "/app" # Location of requirements.txt
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      
  # Maintain dependencies for Node/npm
  - package-ecosystem: "npm"
    directory: "/frontend" # Location of package.json
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      
  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
